version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.blog
    container_name: django_blog_web
    command: bash -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 blog.asgi:application"
    volumes:
      - ./blog:/app
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=blog.settings
    networks:
      - blog_network

  db:
    build:
      context: .
      dockerfile: docker/Dockerfile.db_postgres
    container_name: django_blog_db
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog_network

  celery_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    container_name: celery_worker
    command: celery -A blog_project worker --loglevel=info
    volumes:
      - ./blog:/app
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=blog_project.settings
    networks:
      - blog_network

  celery_beat:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    container_name: celery_beat
    command: celery -A blog_project beat --loglevel=info
    volumes:
      - ./blog:/app
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=blog_project.settings
    networks:
      - blog_network

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    container_name: nginx_blog
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - blog_network

volumes:
  postgres_data:

networks:
  blog_network:
    driver: bridge