FROM python:3.12

WORKDIR /app

RUN apt-get update && apt-get install -y iputils-ping

COPY ./blog/requirements.txt requirements.txt

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY ./blog .